version: '3.7'

services:
  bot:
    container_name: alice_life_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}
    networks:
      - backend_nw
    volumes:
      - ${LOCAL_DIR}/src:/opt/app/src

networks:
  backend_nw:
    driver: bridge